--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 8/13/2021 5:11:17 PM
-- Server version: 5.7.32
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE template_transaction;

--
-- Drop table `order`
--
DROP TABLE IF EXISTS `order`;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Set default database
--
USE template_transaction;

--
-- Create table `user`
--
CREATE TABLE user (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `order`
--
CREATE TABLE `order` (
  id int(11) NOT NULL AUTO_INCREMENT COMMENT '订单id',
  uid int(11) DEFAULT NULL COMMENT '用户id',
  order_info varchar(255) DEFAULT NULL COMMENT '订单信息',
  money decimal(10, 2) DEFAULT NULL COMMENT '订单金额（长度为10保留两位小数）',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

-- 
-- Dumping data for table user
--
-- Table template_transaction.user does not contain any data (it is empty)

-- 
-- Dumping data for table `order`
--
INSERT INTO `order` VALUES
(1, 1, '第一次购买', 0.00),
(2, 1, '非第一次购买', 1.00),
(3, 1, '非第一次购买', 1.00),
(4, 1, '非第一次购买', 1.00),
(5, 1, '非第一次购买', 1.00),
(6, 1, '非第一次购买', 1.00),
(7, 1, '非第一次购买', 1.00),
(8, 1, '非第一次购买', 1.00),
(9, 1, '非第一次购买', 1.00),
(10, 1, '非第一次购买', 1.00);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;